### ISSUE TITLE
La page no esta subida a github pages

### ISSUE THREAD

**Issue by FacundoEG** [NicaOB/page-nicax-dev#1]
Hola Nica! recorda que es una consigna del desafío el que subir la pagina a github pages para corroborar que funciona correctamente, te pediría que revises eso así puedo darte una review.

Saludos!

**Comment by NicaOB** [comment]
Hola Facu, la pagina esta subida, este es el link: https://nicaob.github.io/page-nicax-dev/
Aparece abajo a la derecha en la sección Code de este repo.
¡Saludos!

**Comment by FacundoEG** [comment]
Dale joya ahí la vi! habitualmente suele estar en el readme para acceder mas rápidamente. Cierro issue!
